version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees: kruton
- package-ecosystem: docker
  directory: "/src/test/resources/asyncssh-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees: kruton
- package-ecosystem: docker
  directory: "/src/test/resources/dropbear-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees: kruton
- package-ecosystem: docker
  directory: "/src/test/resources/openssh-server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees: kruton
