language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- "./gradlew bintrayUpload"
env:
  global:
  - bintrayUser=kruton
  - secure: 747rxAH8xAF0LRutqgrb/XlAT0Ju7PfN2lQ7wMjC8arIuDFCDUFgKMfq9qw/fk7KkC058cEXfo8Gmkt9IN//78hxnjMTjS4DRNJYHUm5vFmLIfir1eae9/vNOjJsG+bON9rgzA15smvxJyaGkDLFcLE9Iq7k+qtIdSr1FG6DXkabfAa2zpRs6KkjU10A1HdJ+SNVeXn3vVRULxtxvh0XGKsHrEZbmyVeLRFoaLY8ruJ8FFr2hykQfQ1+XGCLF53dApYpULKWQEkM1EABE7ikX2fM4Xrrn3AlHYGLkd9jnK7drPuR1Q0QqqQC7wwKHLwvXi1CQImRRRV0I9KmlNxsBTN4CxBgw1XfwmFPboofNtewto0DGWe2LqSDP5et3vS6XUX3iHElAiAzwRPMoAXlJVWlo0MsTgA8qUB6bhHgpfnI1M1pBfbgyF70M3lJundm6VYw8/LERhNrmtVPwuJNDugJdvGyMU5XWayKkQj/RPP1x8BEOmpXWLuMA4Vrgo2SSNUCSTm4AzS1kF5M5/hJiR4JkUMie+YKOxrbFAG1CE6uqCMw0Y4oGjVWh+dVR1XfQARrK4fcHF2JIdDj+hibFYGuKY5Uc5S8ShV62QbYRMoXXPfEmLFDY2dAE+Xem45LCLoTfYgUPTPW/rd6erwCfeGC4pOW7B4ndZ+N5WlS+QQ=
