language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
cache:
  directories:
  - "$HOME/.gradle/caches"
before_cache:
- rm -rf $HOME/.gradle/caches/[1-9]*
after_success:
- "./gradlew bintrayUpload"
env:
  global:
  - bintrayUser=kruton
  - secure: p478tZRQdGGiSklfWiMPqLrhTnApfSxqwfCqt3gYExH1fZcRtQL5sR2gopTpFzhD3qbTrGmFA6+BQnOV5O+h1yhZQC3Kup3D2xHnBlSWLLJ/inlsYwHPZX33b86rh45OUuIwASFw57wynWL1I2CDAkAU7z3n0aTmqPqeVc4NoJj71S2dqSF09CEwuxOb7OdiHlzVnWt9rZnWnHhyO8U40paRtOlvt9Xz/poo2i4f5Z/97yVevqiYmPZqr4imvGcH8eGjGbN4oFZV3DFI9KIuhNtX+HFl46c8BjADDNbtx9b/iOUkLnsFhv/nnim1e2RPJDwePiBHXcCR5ONU6L1VW7qG0HxTQPJQfPQZzyCsVBOzoM5UgrAViU6WgMU0K5aiGjYK1fItlzdoJxSa20YzxxLGnoWtYYxLzOLPtEq+KKXghMA8fs6B99rbTSCR3wB9J++IzZMrwN7MPpj39deluRzJfjZrAyiJC7qleKX8PgTNFFbirFCz76W22ZO4YM0McxQqajPzsBFA4AaQaOp1IIKy2rb1kyJ2WprhwO1ruDtZ0KotfgJ9E2UWvGbSe1bUYotkU1AdgS2srx+WCSs8i6mDB0l6BCF1CZ42sDOc1KC6egmEfK7Iqzh+opADhDgDLlBtl1BEipkW+6Tb4gJzn5Vp2f8f+f50oaQXp2TDFf8=
