[versions]
# Plugins
spotless = "8.1.0"
versions = "0.53.0"
nexus-publish = "2.0.0"
release = "3.1.0"
foojay-resolver = "1.0.0"

# Dependencies
simplesocks = "1.0.1"
tink = "1.20.0"
jbcrypt = "1.0.2"
kyber = "2.0.1"
logback = "1.5.22"
commons-codec = "1.20.0"
commons-io = "2.21.0"
hamcrest = "3.0"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "6.0.1"
mockito = "5.21.0"
testcontainers = "2.0.2"

# Build tools
checkstyle = "8.14"

[libraries]
simplesocks = { module = "org.connectbot:simplesocks", version.ref = "simplesocks" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
jbcrypt = { module = "org.connectbot:jbcrypt", version.ref = "jbcrypt" }
kyber = { module = "asia.hombre:kyber", version.ref = "kyber" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
release = { id = "net.researchgate.release", version.ref = "release" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
